/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 fire.gltf --transform
Author: Loïc (https://sketchfab.com/loichuet1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fire-extinguisher-5676b179b3b744c0aaae53a3dcea2300
Title: Fire Extinguisher
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Fire(props) {
  const { nodes, materials } = useGLTF('/fire-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.extincteur} />
    </group>
  )
}

useGLTF.preload('/fire-transformed.glb')
